###########
# site.url, site.title

title: Translationary
url: "https://translationary.onefatgiraffe.com"

# Meta data
# ---------
author:  One Fat Giraffe
keywords:     translation, translation app, translation apps, translations, quran translation - english, google translation, spanish translation, free translation, chinese translation, french translation, translation, quran translation - english, translation widget, translation station, translational medicine, translation dictionary pro, translation recordings, translation+, the translational cancer research podcast from nature reviews cancer, 100 most common english nouns - learn the list of simple words - definition and translation, translate, google translate, translater, translater app free, translate camera, translate app, translate voice, translate english to spanish, translate spanish, translate voice free, aloha, arabic, dialect, dict, dictionary, foreign, france, idiom, iran, korean, languages, pencil, phrases, portuguese, pronunciation, quran, russian, spanishdict, speak, speech, taiwan, text, thesaurus, translate, translator, verbs, version, vocabulary
language:     en
description: The fast, simple and convenient all-in-one app that helps you translate and define your everyday needs.


# Links
# -----
twitter:      onefatgiraffe
instagram:    onefatgiraffe


########
# more settings

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: css
  style:    expanded



exclude: [
  'Gemfile',
  'Gemfile.lock',
  'Rakefile',
  'README.md',
  'node_modules',
  'vendor',
  'bower.json',
  'package.json',
  'gruntfile.js',
  'CONTRIBUTING.md',
  'LICENSE'
  ]


safe: true
lsi: false

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-47364644-6'
